### PR TITLE
fix: Move tests directory into sdk

### PR DESCRIPTION
**Pull request by nand4011**
Move the tests directory into the sdk directory so the project can run them.

### CODE REVIEW

**Review by cprice404 — APPROVED** [review]
:ty:

do we need to do anything to the makefile?

**Comment by cprice404** [comment]
> :ty:
> 
> do we need to do anything to the makefile?

looks like no

🚢

**Comment by nand4011** [comment]
We don't. The makefile commands all run from the sdk directory, and the project assumes there will be a tests directory at the same level as Cargo.toml, so it works.

**Comment by nand4011** [comment]
It does look like the unit tests and integration tests can't be distinguished, so the unit tests step is redundant. It might be worth making a ticket to separate them more.

**Pull request merged**
