### PR TITLE
feat: add dictionary fetch support to the Rust SDK

### PR DESCRIPTION
**Pull request by brayniac**
Adds support for the dictionary fetch command to the Rust SDK.

### CODE REVIEW

**Review by tylerburdsall — DISMISSED** [review]
Looks good to me, understandably the CI build fails since we don't pass along tokens for non-Momento PRs.

I also want to get @kvcache's eyes on this now that he's back, thank you for getting this next API supported!

I imagine down the road with some of our other `dictionary_*` APIs we can DRY up some of the code with a generic function, but that's down the line

**Review by kvcache — COMMENTED** [review]
Looks pretty good, thanks for the contribution. Just 1 question to consider

**Comment by brayniac** [comment]
> Looks pretty good, thanks for the contribution. Just 1 question to consider

Great suggestion there. Committed your diff into this PR.

**Review by kvcache — APPROVED** [review]
L's gtm, thanks

**Comment by brayniac** [comment]
Thanks @kvcache - please merge when able. (I don't have permission to merge to this repo)

**Pull request merged**
