### PR TITLE
refactor: lift sdk to top level

### PR DESCRIPTION
**Pull request by malandis**
Lifts SDK to top level of repo and updates release please to v4.

### CODE REVIEW

**Review by anitarua — COMMENTED** [review]
lgtm. I noticed my SDK automatically updated Cargo.lock though:

```
[[package]]
name = "momento-test-util"
version = "0.1.0"
dependencies = [
 "anyhow",
 "momento",
 "once_cell",
 "scopeguard",
 "tokio",
 "uuid",
]
```

**Comment by malandis** [comment]
> lgtm. I noticed my SDK automatically updated Cargo.lock though:
> 
> ```
> [[package]]
> name = "momento-test-util"
> version = "0.1.0"
> dependencies = [
>  "anyhow",
>  "momento",
>  "once_cell",
>  "scopeguard",
>  "tokio",
>  "uuid",
> ]
> ```

Was this in the PR branch or the main branch? Mine also does that as part of the build the IDE does.

**Comment by malandis** [comment]
> > Was this in the PR branch or the main branch? Mine also does that as part of the build the IDE does.
> 
> Yeah I think rust-analyzer does it. For me, it updated in the PR branch but not main branch

I had to restart VS Code so rust-analyzer would re-generate that. Fixed in https://github.com/momentohq/client-sdk-rust/pull/414/commits/5a912372396724d1a560b911b7ab55f8f82cf3b5

**Review by anitarua — APPROVED** [review]
🎉

**Pull request merged**
