### PR TITLE
feat: add dictionary get and set commands

### PR DESCRIPTION
**Pull request by brayniac**
Adds dictionary get and set commands

### CODE REVIEW

**Comment by brayniac** [comment]
As far as I can tell, this isn't failing due to any code added. Looks like some clippy changes causing lint failures and a "malformed auth token" causing doctest failures.

**Comment by tylerburdsall** [comment]
> As far as I can tell, this isn't failing due to any code added. Looks like some clippy changes causing lint failures and a "malformed auth token" causing doctest failures.

@brayniac That's right, we're also looking to merge https://github.com/momentohq/client-sdk-rust/pull/73 after some changes are made so that clippy warnings are more in-line with our code standards.

Thank you for adding these changes! We can ensure that we add a disclaimer for the `dictionary_*` APIs since they are currently under Preview and require contacting support to enable those APIs for a cache. If you're okay making the suggested Clippy changes we can merge your PR

**Comment by brayniac** [comment]
Thanks @tylerburdsall - working through the clippy lints. Any idea what we need to do to get doctests to pass? Things looked good locally with my own auth token, with exception of the signing key limit eventually causing issues for me with repeated test runs.

**Comment by tylerburdsall** [comment]
@brayniac we'd need to allow-list your auth token, although we can always check out your changes and confirm they work once the Clippy changes are addressed.

We (currently) use this command to check for clippy warnings, so you can always use that to speed up local development:

```bash
cargo clippy --all-targets --all-features -- -D warnings -W clippy::unwrap_used
```

Oh, and something I was looking to add that might speed up the work was to add a `clippy.toml` file in the root of the project with:

```toml
allow-expect-in-tests = true
```

so that you don't have to worry about modifying a bunch of tests.

If you're interested in verifying the workflow yourself, feel free to reach out to @eaddingtonwhite or email `support@momentohq.com` and we can get you set up 😁

**Comment by brayniac** [comment]
@tylerburdsall - the doctests fail in GitHub workflow because of my auth token?

**Comment by tylerburdsall** [comment]
@brayniac Ah apologies, I got ahead of myself. I do see that they are failing because of a malformed auth token, but I would suspect that if that got resolved and you had a non allow-listed token then the tests would fail.

If the build is failing only because of a malformed auth token I can help debug that

**Comment by brayniac** [comment]
Closing in favor of #76

**Pull request closed without merging**
