### PR TITLE
fix: resolve cargo audit errors

### LINKED ISSUE #40: cargo audit failures due to jsonwebtoken 7.2.0
Running cargo audit shows the following issues:

```[client-sdk-rust]$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 404 security advisories (from /home/brian/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (145 crate dependencies)
Crate:         chrono
Version:       0.4.19
Title:         Potential segfault in `localtime_r` invocations
Date:          2020-11-10
ID:            RUSTSEC-2020-0159
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:      No safe upgrade is available!
Dependency tree: 
chrono 0.4.19
└── simple_asn1 0.4.1
    └── jsonwebtoken 7.2.0
        └── momento 0.1.0

Crate:         time
Version:       0.1.43
Title:         Potential segfault in the time crate
Date:          2020-11-18
ID:            RUSTSEC-2020-0071
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:      Upgrade to >=0.2.23
Dependency tree: 
time 0.1.43
└── chrono 0.4.19
    └── simple_asn1 0.4.1
        └── jsonwebtoken 7.2.0
            └── momento 0.1.0

error: 2 vulnerabilities found!
```

### PR DESCRIPTION
**Pull request by brayniac**
Resolves the cargo audit errors by upgrading jsonwebtoken to 8.0.1
and making necessary code changes.

Fixes #40

### CODE REVIEW

**Review by bruuuuuuuce — APPROVED** [review]
:shipit: looks great, thanks!

**Comment by brayniac** [comment]
@bruuuuuuuce Will ping for review again after I fix the test failures. Is there a good process for running doc tests / integration tests locally?

**Comment by bruuuuuuuce** [comment]
> @bruuuuuuuce Will ping for review again after I fix the test failures. Is there a good process for running doc tests / integration tests locally?

To run doc tests you can run `cargo test --doc`. To run int tests you can run `cargo test --tests`

**Comment by brayniac** [comment]
> > @bruuuuuuuce Will ping for review again after I fix the test failures. Is there a good process for running doc tests / integration tests locally?
> 
> To run doc tests you can run `cargo test --doc`. To run int tests you can run `cargo test --tests`

I meant as far as those needing a token. Is any valid auth token fine, or do we need to have certain caches created before running the tests?

**Comment by bruuuuuuuce** [comment]
> > > @bruuuuuuuce Will ping for review again after I fix the test failures. Is there a good process for running doc tests / integration tests locally?
> > 
> > 
> > To run doc tests you can run `cargo test --doc`. To run int tests you can run `cargo test --tests`
> 
> I meant as far as those needing a token. Is any valid auth token fine, or do we need to have certain caches created before running the tests?

Ah yes any valid token is fine. You should not need to have any caches precreated to run the tests afaik

**Comment by brayniac** [comment]
@bruuuuuuuce - can you look at the CI failure. It seems the token is empty during the CI run resulting in the failure. Same is causing an issue in #42 which doesn't mess with any of the token code. Ping me on slack if it's easier to discuss there. Thanks!

**Pull request closed without merging**
